trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main


pool:
  vmImage: 'ubuntu-latest'

variables:
  solutionFolder: 'ApiAutomationTests'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: Checkout@1

  - script: |
      cd $(solutionFolder)
      dotnet restore
    displayName: 'Restore dependencies'

  - script: |
      cd $(solutionFolder)
      dotnet build --no-restore
    displayName: 'Build project'

  - script: |
      cd $(solutionFolder)
      dotnet test --no-build --logger:"console;verbosity=normal"
    displayName: 'Run tests'

